# Generated by Django 5.2 on 2025-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quote",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Motivational", "Motivational"),
                    ("Love", "Love"),
                    ("Life", "Life"),
                    ("Funny", "Funny"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
